version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - "./:/usr/src/app"
    ports:
      - "3000:3000"

  db:
    image: mysql
    command: --authentication_policy=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_database
    ports:
      - "3306:3306"
